#!/bin/sh

php artisan migrate:refresh --seed
php artisan cache:clear

curl http://qa.craftingasaservice.com/gathering/list/MIN >> /dev/null&
curl http://qa.craftingasaservice.com/gathering/list/BTN >> /dev/null&